# Generated by Django 3.1.2 on 2020-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='email address', max_length=100)),
                ('full_name', models.CharField(help_text='full name', max_length=100)),
            ],
        ),
    ]
